# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('weight', models.IntegerField(default='0')),
                ('num_of_workout_days', models.IntegerField(default='1')),
                ('workout_choice', models.CharField(choices=[('cardio', 'Cardio'), ('weights', 'Weights'), ('mixed', 'Mixed')], default='mixed', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('workout_type', models.CharField(max_length=7)),
                ('workout_region', models.CharField(default='', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout_user', models.ManyToManyField(related_name='user_workout', to='lift_final.User')),
            ],
        ),
    ]
